name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: example.com  # Uncomment and set if you use a custom domain
          CONFIG_FILE: mkdocs.yml
          # REQUIREMENTS: requirements.txt  # Uncomment if you add a requirements.txt
          # EXTRA_PACKAGES: build-base     # Uncomment if you need extra system packages 